# Generated by Django 5.0.2 on 2024-03-01 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название варианта')),
                ('active', models.BooleanField(default=False, verbose_name='Текущий вариант')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('first_counter_name', models.CharField(max_length=100, verbose_name='Название счетчика 1')),
                ('first_counter', models.IntegerField(default=178, verbose_name='Счетчик 1')),
                ('first_counter_icon', models.CharField(max_length=50, verbose_name='Иконка счетчика 1')),
                ('second_counter_name', models.CharField(max_length=100, verbose_name='Название счетчика 2')),
                ('second_counter', models.IntegerField(default=178, verbose_name='Счетчик 2')),
                ('second_counter_icon', models.CharField(max_length=50, verbose_name='Иконка счетчика 2')),
                ('third_counter_name', models.CharField(max_length=100, verbose_name='Название счетчика 3')),
                ('third_counter', models.IntegerField(default=178, verbose_name='Счетчик 3')),
                ('third_counter_icon', models.CharField(max_length=50, verbose_name='Иконка счетчика 3')),
                ('fourth_counter_name', models.CharField(max_length=100, verbose_name='Название счетчика 4')),
                ('fourth_counter', models.IntegerField(default=178, verbose_name='Счетчик 4')),
                ('fourth_counter_icon', models.CharField(max_length=50, verbose_name='Иконка счетчика 4')),
                ('why_title', models.CharField(max_length=100, verbose_name='Заголовок блока почему')),
                ('why_image', models.ImageField(upload_to='media/about', verbose_name='Изображение блока почему')),
                ('why_description', models.TextField(verbose_name='Описание блока почему')),
                ('reason_one_title', models.CharField(max_length=100, verbose_name='Заголовок причины 1')),
                ('reason_one_description', models.TextField(verbose_name='Описание причины 1')),
                ('reason_one_icon', models.CharField(max_length=50, verbose_name='Иконка причины 1')),
                ('reason_two_title', models.CharField(max_length=100, verbose_name='Заголовок причины 2')),
                ('reason_two_description', models.TextField(verbose_name='Описание причины 2')),
                ('reason_two_icon', models.CharField(max_length=50, verbose_name='Иконка причины 2')),
                ('reason_three_title', models.CharField(max_length=100, verbose_name='Заголовок причины 3')),
                ('reason_three_description', models.TextField(verbose_name='Описание причины 3')),
                ('reason_three_icon', models.CharField(max_length=50, verbose_name='Иконка причины 3')),
            ],
            options={
                'verbose_name': 'Вариант О нас',
                'verbose_name_plural': 'Варианты блока О Нас',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('phone', models.CharField(max_length=18, verbose_name='Телефон')),
                ('map_link', models.CharField(max_length=1000, verbose_name='Ссылка на карту')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контактная информация',
            },
        ),
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наимевание')),
            ],
            options={
                'verbose_name': 'Категория услуг',
                'verbose_name_plural': 'Категории услуг',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('image', models.ImageField(upload_to='media/projects', verbose_name='Изображение')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.CharField(max_length=50, verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/galleries', verbose_name='Изображение')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mebel_app.gallerycategory', verbose_name='Категоория изображений')),
            ],
            options={
                'verbose_name': 'Изображение услуги',
                'verbose_name_plural': 'Изображения услуг',
            },
        ),
    ]
