# Generated by Django 5.0.2 on 2024-03-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel_app', '0003_alter_gallerycategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Основной'),
        ),
    ]
