# Generated by Django 5.0.2 on 2024-03-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel_app', '0004_contact_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='palax_image',
            field=models.ImageField(blank=True, upload_to='media/palax', verbose_name='Изображение паралакс'),
        ),
    ]
