# Generated by Django 5.0.2 on 2024-03-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel_app', '0008_employee_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.CharField(default=1, max_length=250, verbose_name='Краткое описание'),
            preserve_default=False,
        ),
    ]
