# Generated by Django 5.0.2 on 2024-03-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel_app', '0010_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='icon',
            field=models.CharField(default=1, max_length=50, verbose_name='Тег иконки'),
            preserve_default=False,
        ),
    ]
